name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: ./builddir/
        id: dockerstep
        with:
          who-to-greet: "Mona the Octocat"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      #      - name: Create Release#
      #        id: create_release
      #        uses: actions/create-release@v1
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #        with:
      #          tag_name: ${{ github.ref }}${{ steps.dockerstep.outputs.time2 }}
      #          release_name: Release ${{ github.ref }}${{ steps.dockerstep.outputs.time2 }}
      #          body: |
      #            Changes in this Release
      #            - First Change ${{ steps.dockerstep.outputs.time }}
      #            - Second Change ${{ steps.dockerstep.outputs.time2 }}
      #          draft: false
      #          prerelease: false
      #
      - name: Upload Release Asset ${{ steps.create_release.outputs.upload_url }}
        id: upload-release-asset
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          #upload_url: ${{ steps.create_release.outputs.upload_url }}
          upload_url: https://uploads.github.com/repos/predkambrij/testRepo/releases/25427353/assets{?name,label}
          asset_path: ./artifact.zip
          asset_name: artifact_${{ steps.dockerstep.outputs.gitbranchname }}_${{ steps.dockerstep.outputs.time2 }}_${{ steps.dockerstep.outputs.gitsha }}.zip
          asset_content_type: application/zip
